### ISSUE TITLE
Add API exporter

### ISSUE THREAD

**Issue by puja108** [giantswarm/kubernetes-prometheus#10]
This little tool https://github.com/tomwilkie/kube-api-exporter/ helps making API data available in kubernetes so you can monitor for example if deployments succeeded or failed. Really cool especially if you have an automated CI/CD setup. Could be interesting for our users.

**Comment by puja108** [comment]
You can setup stuff like alerts based on „no more available replicas“ and „only one replica left“ with different escalation levels so the ops team knows when the cluster is full.

**Comment by pipo02mix** [comment]
No longer valid
