### ISSUE TITLE
Not Working on Kubernetes 1.4.4

### ISSUE THREAD

**Issue by kaverappa-ib** [giantswarm/kubernetes-prometheus#20]
We just upgraded to kubernetes 1.4.4 and grafana cannnot populate data

**Comment by webwurst** [comment]
On the Kubernetes side a label name changed. It is now `pod_name` instead of `io_kubernetes_pod_name`. This is fixed by #21. You can also try to just import this updated dashboard:
https://grafana.net/dashboards/737

Does this work for you? Or do you see another error?

**Comment by kaverappa-ib** [comment]
now it works great. Even better with the updated dashboard, which pulls up most of my required monitoring parameters, Thank you.
