### ISSUE TITLE
add new informative cluster dashboard

### ISSUE THREAD

**Issue by puja108** [giantswarm/kubernetes-prometheus#3]
Add new or change the standard k8s grafana dashboard to fit a typical GS user better.

Some things to consider:

- [ ] resource usage per node (+ worker)
- [ ] anything else?

**Comment by JosephSalisbury** [comment]
What is the "standard k8s grafana dashboard"? What does it look like?

**Comment by puja108** [comment]
@JosephSalisbury this https://grafana.net/dashboards/162

**Comment by JosephSalisbury** [comment]
![image](https://cloud.githubusercontent.com/assets/297653/17476579/acf88aaa-5d58-11e6-9045-57eaed2b8c05.png)
this is what i see there

i am strongly against those gauges - those things tell me next to nothing. pod memory / cpu usage looks useful though. line graphs ftw

**Comment by puja108** [comment]
yeah, we talked about this a bit and most people commented on the gauges looking nice but not being useful, we might want to replace them with graphs and split up by node

**Comment by JosephSalisbury** [comment]
yeah, they look cool, but averages kind of suck - per node line graphs sounds good
