### ISSUE TITLE
Blogpost: Use readiness probe when waiting on Grafana

### ISSUE THREAD

**Issue by webwurst** [giantswarm/kubernetes-prometheus#33]

**Comment by othylmann** [comment]
Neofonie needs their signal ready stuff and the idea is to build an example through a probe system in kubernetes to show them. Hence, blog post. Content. Traffic. Yiha :)

**Comment by othylmann** [comment]
I heard that you worked on the readiness probe? When can we expect the blogpost. We need to talk to Neofonie.

**Comment by marians** [comment]
Published!
