### ISSUE TITLE
imagePullPolicy: Required Value

### ISSUE THREAD

**Issue by v1k0d3n** [giantswarm/kubernetes-prometheus#40]
Seems like this deployment is also impacted by the recent [Kubernetes issue](https://github.com/kubernetes/kubernetes/issues/38542):

```
The Job "grafana-import-dashboards" is invalid: spec.template.spec.initContainers[0].imagePullPolicy: Required value
```

Just wanted to let you know in case you decided to use the recommended [work around](https://github.com/kubernetes/charts/commit/7d2b14da452277a63c4c98e5176f79663af2cb28).

**Comment by webwurst** [comment]
Fixed by #41
