### ISSUE TITLE
Add blackbox-exporter and alert-manager

### ISSUE THREAD

**Issue by webwurst** [giantswarm/kubernetes-prometheus#43]

**Comment by cemo** [comment]
Yes please :) 👍

**Comment by RahulMahale** [comment]
@puja108 is someone working on it or should I come up with alertmanager templates ?

**Comment by puja108** [comment]
I think @MarcelMue is working on alert manager in a branch right now: https://github.com/giantswarm/kubernetes-prometheus/tree/add-alert-manager

If he opens a PR happy if you chime in.

@webwurst Not sure why this issue includes blackbox-exporter? What is that about and shouldn't it be separate from alertmanager?

**Comment by MarcelMue** [comment]
I have opened a PR ( #65 ), feel free to review/give advice.
