### ISSUE TITLE
add a quick TLDR way of deploying

### ISSUE THREAD

**Issue by puja108** [giantswarm/kubernetes-prometheus#5]
For those in a hurry or just wanting to set it up again (like me for the nth time now) it would be cool to have a TLDR way (a script or compressed YAMLs or something) to get to a running state.

What do you think @webwurst ?

**Comment by webwurst** [comment]
It should be enough to just run `kubectl create --filename *.yaml`. If need we should fix that.

**Comment by puja108** [comment]
true, I'll test it and then add it somewhere in docs or readme

**Comment by webwurst** [comment]
We could move all the manifests to `/manifests` and then use `kubectl create --filename manifests/`. Feels a bit cleaner.

**Comment by webwurst** [comment]
And we should provide the initial Grafana configuration for datasource and dashboards.

**Comment by webwurst** [comment]
I'll have a look at the created Grafana configuration and come up with a `grafana-configmap.yaml`.
