### ISSUE TITLE
No datapoints in CPU Usage graph for pods

### ISSUE THREAD

**Issue by jackjacek** [giantswarm/kubernetes-prometheus#50]
Hello,

Seems CPU usage stats disappear shortly after deploying. Tried adjusting cpu & memory which helped the graphs to load quicker and temporarily fixed the cpu usage graph however shortly afterwards issue resurfaced. 
As a side note: query in another dashboard for cpu stats seems to work `sum (rate (container_cpu_usage_seconds_total{image!="",name=~"^k8s_.*",kubernetes_io_hostname=~"^$Node$"}[1m])) by (pod_name)`

Hope this helps!

**Comment by pipo02mix** [comment]
done https://github.com/giantswarm/kubernetes-prometheus/pulls/104
