### ISSUE TITLE
Cannot get Grafana to work

### ISSUE THREAD

**Issue by achanda** [giantswarm/kubernetes-prometheus#86]
I followed the quickstart doc and ran
 `kubectl apply
  --filename https://raw.githubusercontent.com/giantswarm/kubernetes-prometheus/master/manifests-all.yaml`

Now when I login to Grafana, the default Kubernetes Pod Resources dashboard shows N/A for all metrics. All components are in running state and no errors in any logs. Am I missing some other config?

**Comment by ziXet** [comment]
Same. It was fine on k8s 1.6 but 1.7 not working.

**Comment by peterdeme** [comment]
I get the same on 1.8

**Comment by c-rainstorm** [comment]
Same. k8s 1.10

**Comment by ZhengRongTan** [comment]
I get the same on k8s 1.8.5

**Comment by runam0K** [comment]
Same. k8s 1.10. Is there no solution?

**Comment by mo-mirzania** [comment]
I get the same issue on k8s 1.10

**Comment by mglagad** [comment]
facing same issue with 1.10. is there any update on this?

**Comment by hzio** [comment]
I get the same issue on k8s v1.11.1

**Comment by indraforyou** [comment]
same issue on v1.11.2.

**Comment by kleuf** [comment]
same issue in v1.11.3

**Comment by kleuf** [comment]
its not a rbac issue, as i have basically given the service account access to do anything

**Comment by crackoffnet** [comment]
Any news on this?

**Comment by ethems** [comment]
Make sure your browser and server are in the same time zone

**Comment by c0bra** [comment]
I think this project is defunct. Seems like the metric names are all different in k8s 1.10+, or even earlier

**Comment by mikescholze** [comment]
same issue in v1.11.3 too

**Comment by pipo02mix** [comment]
Done https://github.com/giantswarm/kubernetes-prometheus/pull/73
